import "./globals.css";
import "@repo/ui/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "../trpc/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <TRPCReactProvider>
          <main>{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
